version: '3'

services:
  app:
    container_name: cc_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      DB_CONNECTION: "mysql"
      DB_HOST: "db"
      DB_PORT: "3306"
      DB_DATABASE: "lumen"
      DB_USERNAME: "root"
      DB_PASSWORD: "password"
    volumes:
      - .:/var/www
    depends_on:
      - db

  db:
    container_name: cc_db
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "lumen"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db-data:/var/lib/mysql

  web:
    container_name: cc_nginx
    image: nginx:latest
    restart: always
    ports:
      - "8002:80"
    volumes:
      - .:/var/www
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db-data:
